### PR TITLE
Support zeitwerk loading (0.18.0)

### PR DESCRIPTION
**Pull request by Noah-Silvera**
What is the goal of this PR?
---

Support loading this extension with the zeitwork loader

This is a breaking change due the renaming of the module

How do you manually test these changes? (if applicable)
---

1. Set up this gem in a rails project that uses zeitwork
    * [x] Ensure it loads properly and can be used to calculate taxes

Merge Checklist
---

- [x] Run the manual tests
- [x] Update the changelog

### CODE REVIEW

**Comment by Noah-Silvera** [comment]
@AdnanTheExcellent @nvandoorn and I don't quite understand the requirement for `active_storage` is needed? What required the dependency in your original PR #32 ? Thanks :)

**Comment by AdnanTheExcellent** [comment]
@Noah-Silvera attaching the tax exemption documents. each exempt region has an attached tax exemption form. 

our tax exempt customer flow is:

1. The user creates a tax exemption (taxjar customer) with many exempt regions in their account settings. they submit their tax exempt forms and submit it to us.
2. Customer service (solidus admin) sees the requests, checks the tax exempt forms, and approves / rejects them in Solidus admin. Then the tax exempt forms are handled as necessary (outside scope of this extension), such as uploading them in taxjar admin or filing them somewhere else outside of solidus.

**Comment by Noah-Silvera** [comment]
@AdnanTheExcellent that makes sense! We will let you make that breaking change in your PR then.

**Comment by Noah-Silvera** [comment]
@AdnanTheExcellent  and @jarednorman we decided to make the upgrade to the zeitwork loaders **not** a 1.0.0 release as @nvandoorn brought up an excellent point that breaking changes as minor version changes when the version is below 1.X are acceptable in a lot of projects.

We envision a couple more breaking changes we will need to make in the near future (for example, @AdnanTheExcellent 's work in #32), and we don't want to end up at version 6.X within the next 6 months.

**Review by adammathys — APPROVED** [review]

**Comment by jarednorman** [comment]
@Noah-Silvera I'm not sure if I put this anywhere, but I'd like to see if there's a way to resolve the migration issue that @AdnanTheExcellent identified without renaming the extension. If this is the only reasonable option, that's fine, but if there's a way to stick with the conventional naming, then I'd prefer to do that.

**Comment by Noah-Silvera** [comment]
@jarednorman we gave it a test and the gem doesn't seem to need a rename in order to support rails 6.
@AdnanTheExcellent unless we've missed a reason we need the gem rename, i've dropped the commit.

**Comment by jarednorman** [comment]
Sorry, that conversation was in DMs, here's the explanation from Adnan:

> the name `super_good-solidus_taxjar` breaks some things like install generators installing migrations due to the hyphen in the name. the migrations ported over will have `.super_good-solidus_tax_jar` appended to it which gives a `ActiveRecord::IllegalMigrationNameError` from the hyphen.

**Comment by Noah-Silvera** [comment]
> Sorry, that conversation was in DMs, here's the explanation from Adnan:
> 
> > the name `super_good-solidus_taxjar` breaks some things like install generators installing migrations due to the hyphen in the name. the migrations ported over will have `.super_good-solidus_tax_jar` appended to it which gives a `ActiveRecord::IllegalMigrationNameError` from the hyphen.

Ahh ok, that makes sense!

Since the migrations aren't introduced until #32, Nick and I can tackle solving that problem in a different PR, and get this one through, as it adds value in itself.

**Review by AdnanTheExcellent — APPROVED** [review]
LGTM

**Review by jarednorman — APPROVED** [review]

**Pull request merged**
