### PR TITLE
Improve error handling for `ReportTransactionJob`

### PR DESCRIPTION
**Pull request by benjaminwil**
What is the goal of this PR?
---

This pull request resolves a user reported error, #248.

Merge Checklist
---

- [x] Update the changelog

### CODE REVIEW

**Review by forkata — APPROVED** [review]
LGTM, should we add a spec for this change?

**Comment by benjaminwil** [comment]
There is an existing spec for raising an error from the job. It didn't seem valuable to me to make a second one with a different error class.

**Comment by forkata** [comment]
> There is an existing spec for raising an error from the job. It didn't seem valuable to me to make a second one with a different error class.

We could change the type of error raised I guess 🤔

**Comment by benjaminwil** [comment]
Okay, I have been convinced. I will add an additional test for `StandardError` rescuing specifically.

**Comment by forkata** [comment]
Rebased to resolve conflicts.

**Pull request merged**
