### PR TITLE
Andrey/adnan/solidus 4.0

### PR DESCRIPTION
**Pull request by ashgaliyev**

### CODE REVIEW

**Comment by forkata** [comment]
Hey @ashgaliyev, did you mean to open this PR?

**Comment by ashgaliyev** [comment]
> Hey @ashgaliyev, did you mean to open this PR?

No, sorry, it was by accident.

**Comment by kevin-jj** [comment]
Would it be possible to merge this PR? @ashgaliyev @forkata

**Comment by forkata** [comment]
Hey @kevin-jj, I don't think the PR makes sense in this reporsitory the way it was written. If there is an issue you are having please feel free to open and we can address it. Are you looking for Solidus 4 support?

**Pull request closed without merging**
